/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.ClsSQLQuery;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Will Vasquez
 */
public final class FrmIdioma extends javax.swing.JDialog {
     JMenu jMenu5 = new javax.swing.JMenu();
     JMenu jMenu6 = new javax.swing.JMenu();
     JMenu jMenu7 = new javax.swing.JMenu();

    /**
     * Creates new form FrmIdioma
     * @param parent
     * @param modal
     */
    public FrmIdioma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Diseño/Idioma.png")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        lbltitulo = new javax.swing.JLabel();
        PnlContenedor = new javax.swing.JPanel();
        BtnEspañol = new javax.swing.JButton();
        BtnEnglish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Seleccion de idioma");

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PnlContenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Seleccione su idioma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white)); // NOI18N
        PnlContenedor.setOpaque(false);

        BtnEspañol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/ESP2.png"))); // NOI18N
        BtnEspañol.setBorder(null);
        BtnEspañol.setBorderPainted(false);
        BtnEspañol.setContentAreaFilled(false);
        BtnEspañol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEspañol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEspañol.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/ESP1.png"))); // NOI18N
        BtnEspañol.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/ESP3.png"))); // NOI18N
        BtnEspañol.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnEspañol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEspañolActionPerformed(evt);
            }
        });

        BtnEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/US2.png"))); // NOI18N
        BtnEnglish.setBorder(null);
        BtnEnglish.setBorderPainted(false);
        BtnEnglish.setContentAreaFilled(false);
        BtnEnglish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEnglish.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEnglish.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/US1.png"))); // NOI18N
        BtnEnglish.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/US3.png"))); // NOI18N
        BtnEnglish.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnEnglish.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnglishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContenedorLayout = new javax.swing.GroupLayout(PnlContenedor);
        PnlContenedor.setLayout(PnlContenedorLayout);
        PnlContenedorLayout.setHorizontalGroup(
            PnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnEspañol, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(BtnEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PnlContenedorLayout.setVerticalGroup(
            PnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenedorLayout.createSequentialGroup()
                .addGroup(PnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEspañol, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(BtnEnglish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnglishActionPerformed
        IdiomaEnglish();
        ClsSQLQuery obj = new ClsSQLQuery();
        obj.setIdioma(2);
        if(obj.CambiarIdioma()){
            JOptionPane.showMessageDialog(this, "Language changed successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
            BtnEnglish.setEnabled(false);
            BtnEspañol.setEnabled(true);
        }
    }//GEN-LAST:event_BtnEnglishActionPerformed

    private void BtnEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEspañolActionPerformed
        IdiomaEspañol();
        ClsSQLQuery obj = new ClsSQLQuery();
        obj.setIdioma(1);
        if(obj.CambiarIdioma()){
            JOptionPane.showMessageDialog(this, "Idioma cambiado satisfactoriamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            BtnEspañol.setEnabled(false);
            BtnEnglish.setEnabled(true);
            FrmPrincipal.BarraMenu.remove(FrmPrincipal.jMenu5);
            FrmPrincipal.BarraMenu.remove(FrmPrincipal.jMenu6);
            FrmPrincipal.BarraMenu.remove(FrmPrincipal.jMenu7);
        }
    }//GEN-LAST:event_BtnEspañolActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ClsSQLQuery obj = new ClsSQLQuery();
        if(obj.ConsultarIdioma()){
            if(obj.getIdioma() == 1){
                FrmPrincipal.MenuUsuarios.setText("Usuarios");
                FrmPrincipal.MenuTipoUsuario.setText("Tipo de usuarios");
                FrmPrincipal.MenuUsuarios2.setText("Usuarios");
                FrmPrincipal.MenuContaduria.setText("Cambiar contraseña");
                FrmPrincipal.MenuGeneral.setText("Establecimiento");
                FrmPrincipal.MenuDatos.setText("Datos del parqueo");
                FrmPrincipal.MenuTarifas.setText("Precios");
                FrmPrincipal.MenuNuevoVehiculo.setText("Nuevo vehiculo");
                FrmPrincipal.MenuParqueo.setText("Parqueo");
                FrmPrincipal.MenuPuestos.setText("Puestos");
                FrmPrincipal.MenuParquear.setText("Parquear vehiculo");
                FrmPrincipal.MenuRetirar.setText("Retirar vehiculo");
                FrmPrincipal.MenuAlquiler.setText("Servicio de alquiler");
                FrmPrincipal.MenuContaduria.setText("Finanzas");
                FrmPrincipal.MenuGanancia.setText("Ganancias obtenidas");
                FrmPrincipal.MenuReportes.setText("Reportes");
                FrmPrincipal.MenuUsuarios3.setText("Usuarios");
                FrmPrincipal.MenuUsuarios4.setText("Usuarios registrados");
                FrmPrincipal.MenuTipoUsuarios2.setText("Tipos de usuarios registrados");
                FrmPrincipal.MenuHistorial.setText("Historial de inicios de sesión");
                FrmPrincipal.MenuClientes.setText("Clientes");
                FrmPrincipal.MenuClientes2.setText("Clientes ingresados al parqueo");
                FrmPrincipal.MenuClientes3.setText("Clientes retirados del parqueo");
                FrmPrincipal.MenuVehiculos.setText("Vehiculos");
                FrmPrincipal.MenuIngresados.setText("Vehiculos livianos");
                FrmPrincipal.MenuRetirados.setText("Vehiculos comerciales");
                FrmPrincipal.MenuVIP.setText("vehiculos VIP");
                FrmPrincipal.MenuMoto.setText("Motocicletas");
                FrmPrincipal.MenuTipoVehiculos.setText("Tipos de vehiculos");
                FrmPrincipal.MenuFinanzas.setText("Finanzas");
                FrmPrincipal.MenuTotal.setText("Ganancias totales del parqueo");
                FrmPrincipal.MenuTotal2.setText("Ganancias totales del alquiler");
                FrmPrincipal.MenuInterfaz.setText("Interfaz");
                FrmPrincipal.MenuBaseDatos.setText("Base de datos");
                FrmPrincipal.MenuAyuda.setText("Otros");
                FrmPrincipal.MenuAutores.setText("Creadores");
                FrmPrincipal.MenuReporte.setText("Reporte tecnico");
                FrmPrincipal.MenuMusica.setText("Reproduce tu musica");
                FrmPrincipal.MenuIdioma.setText("Idioma del sistema");
                FrmPrincipal.MenuSesion.setText("Cerrar sesión");
                FrmPrincipal.MenuSalir.setText("Salir");
                BtnEnglish.setEnabled(true);
                BtnEspañol.setEnabled(false);
            }
            else{
                FrmPrincipal.MenuUsuarios.setText("Users");
                FrmPrincipal.MenuTipoUsuario.setText("Type of user");
                FrmPrincipal.MenuUsuarios2.setText("Users");
                FrmPrincipal.MenuContaduria.setText("Change password");
                FrmPrincipal.MenuGeneral.setText("Establishment");
                FrmPrincipal.MenuDatos.setText("Details parking");
                FrmPrincipal.MenuTarifas.setText("Prices");
                FrmPrincipal.MenuNuevoVehiculo.setText("New vehicle");
                FrmPrincipal.MenuParqueo.setText("Parking");
                FrmPrincipal.MenuPuestos.setText("Places");
                FrmPrincipal.MenuParquear.setText("Vehicle parking");
                FrmPrincipal.MenuRetirar.setText("Remove Vehicle");
                FrmPrincipal.MenuAlquiler.setText("Rental Service");
                FrmPrincipal.MenuContaduria.setText("Finance");
                FrmPrincipal.MenuGanancia.setText("Gains");
                FrmPrincipal.MenuReportes.setText("Reports");
                FrmPrincipal.MenuUsuarios3.setText("Users");
                FrmPrincipal.MenuUsuarios4.setText("Registered users");
                FrmPrincipal.MenuTipoUsuarios2.setText("Types of users registered");
                FrmPrincipal.MenuHistorial.setText("History of logins");
                FrmPrincipal.MenuClientes.setText("Client");
                FrmPrincipal.MenuClientes2.setText("Client entered in the parking");
                FrmPrincipal.MenuClientes3.setText("Client remove of the parking");
                FrmPrincipal.MenuVehiculos.setText("Vehicle");
                FrmPrincipal.MenuIngresados.setText("Light vehicles");
                FrmPrincipal.MenuRetirados.setText("Commercial vehicles");
                FrmPrincipal.MenuVIP.setText("VIP vehicles");
                FrmPrincipal.MenuMoto.setText("Motorcycles");
                FrmPrincipal.MenuTipoVehiculos.setText("Types of vehicles");
                FrmPrincipal.MenuFinanzas.setText("Finance");
                FrmPrincipal.MenuTotal.setText("Total gains of the parking");
                FrmPrincipal.MenuTotal2.setText("Total gains of rent");
                FrmPrincipal.MenuInterfaz.setText("Interface");
                FrmPrincipal.MenuBaseDatos.setText("DataBase");
                FrmPrincipal.MenuAyuda.setText("Others");
                FrmPrincipal.MenuAutores.setText("Creators");
                FrmPrincipal.MenuReporte.setText("Technical report");
                FrmPrincipal.MenuMusica.setText("Play your music");
                FrmPrincipal.MenuIdioma.setText("System Language");
                FrmPrincipal.MenuSesion.setText("Sign off");
                FrmPrincipal.MenuSalir.setText("Exit");
                BtnEspañol.setEnabled(true);
                BtnEnglish.setEnabled(false);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    public void IdiomaEnglish(){
        lbltitulo.setText("Language selection");
        PnlContenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Select your language", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white));
        this.setTitle("Language");
        FrmPrincipal.MenuUsuarios.setText("Users");
        FrmPrincipal.MenuTipoUsuario.setText("Type of user");
        FrmPrincipal.MenuUsuarios2.setText("Users");
        FrmPrincipal.MenuContaduria.setText("Change password");
        FrmPrincipal.MenuGeneral.setText("Establishment");
        FrmPrincipal.MenuDatos.setText("Details parking");
        FrmPrincipal.MenuTarifas.setText("Prices");
        FrmPrincipal.MenuNuevoVehiculo.setText("New vehicle");
        FrmPrincipal.MenuParqueo.setText("Parking");
        FrmPrincipal.MenuPuestos.setText("Places");
        FrmPrincipal.MenuParquear.setText("Vehicle parking");
        FrmPrincipal.MenuRetirar.setText("Remove Vehicle");
        FrmPrincipal.MenuAlquiler.setText("Rental Service");
        FrmPrincipal.MenuContaduria.setText("Finance");
        FrmPrincipal.MenuGanancia.setText("Gains");
        FrmPrincipal.MenuReportes.setText("Reports");
        FrmPrincipal.MenuUsuarios3.setText("Users");
        FrmPrincipal.MenuUsuarios4.setText("Registered users");
        FrmPrincipal.MenuTipoUsuarios2.setText("Types of users registered");
        FrmPrincipal.MenuHistorial.setText("History of logins");
        FrmPrincipal.MenuClientes.setText("Client");
        FrmPrincipal.MenuClientes2.setText("Client entered in the parking");
        FrmPrincipal.MenuClientes3.setText("Client remove of the parking");
        FrmPrincipal.MenuVehiculos.setText("Vehicle");
        FrmPrincipal.MenuIngresados.setText("Light vehicles");
        FrmPrincipal.MenuRetirados.setText("Commercial vehicles");
        FrmPrincipal.MenuVIP.setText("VIP vehicles");
        FrmPrincipal.MenuMoto.setText("Motorcycles");
        FrmPrincipal.MenuTipoVehiculos.setText("Types of vehicles");
        FrmPrincipal.MenuFinanzas.setText("Finance");
        FrmPrincipal.MenuTotal.setText("Total gains of the parking");
        FrmPrincipal.MenuTotal2.setText("Total gains of rent");
        FrmPrincipal.MenuInterfaz.setText("Interface");
        FrmPrincipal.MenuBaseDatos.setText("DataBase");
        FrmPrincipal.MenuAyuda.setText("Others");
        FrmPrincipal.MenuAutores.setText("Creators");
        FrmPrincipal.MenuReporte.setText("Technical report");
        FrmPrincipal.MenuMusica.setText("Play your music");
        FrmPrincipal.MenuIdioma.setText("System Language");
        FrmPrincipal.MenuSesion.setText("Sign off");
        FrmPrincipal.MenuSalir.setText("Exit");
        jMenu5.setBackground(new java.awt.Color(0, 0, 0));
        jMenu5.setText(" ᅝᅝᅝ");
        jMenu5.setOpaque(true);
        FrmPrincipal.BarraMenu.add(jMenu5);
        jMenu6.setBackground(new java.awt.Color(0, 0, 0));
        jMenu6.setText(" ᅝᅝᅝ");
        jMenu6.setOpaque(true);
        FrmPrincipal.BarraMenu.add(jMenu6);
        jMenu7.setBackground(new java.awt.Color(0, 0, 0));
        jMenu7.setText(" ᅝᅝᅝ");
        jMenu7.setOpaque(true);
        FrmPrincipal.BarraMenu.add(jMenu7);
    }
    
    public void IdiomaEspañol(){
        lbltitulo.setText("Seleccion de idioma");
        PnlContenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Seleccione su idioma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white));
        this.setTitle("Idioma");
        FrmPrincipal.MenuUsuarios.setText("Usuarios");
        FrmPrincipal.MenuTipoUsuario.setText("Tipo de usuarios");
        FrmPrincipal.MenuUsuarios2.setText("Usuarios");
        FrmPrincipal.MenuContaduria.setText("Cambiar contraseña");
        FrmPrincipal.MenuGeneral.setText("Establecimiento");
        FrmPrincipal.MenuDatos.setText("Datos del parqueo");
        FrmPrincipal.MenuTarifas.setText("Precios");
        FrmPrincipal.MenuNuevoVehiculo.setText("Nuevo vehiculo");
        FrmPrincipal.MenuParqueo.setText("Parqueo");
        FrmPrincipal.MenuPuestos.setText("Puestos");
        FrmPrincipal.MenuParquear.setText("Parquear vehiculo");
        FrmPrincipal.MenuRetirar.setText("Retirar vehiculo");
        FrmPrincipal.MenuAlquiler.setText("Servicio de alquiler");
        FrmPrincipal.MenuContaduria.setText("Finanzas");
        FrmPrincipal.MenuGanancia.setText("Ganancias obtenidas");
        FrmPrincipal.MenuReportes.setText("Reportes");
        FrmPrincipal.MenuUsuarios3.setText("Usuarios");
        FrmPrincipal.MenuUsuarios4.setText("Usuarios registrados");
        FrmPrincipal.MenuTipoUsuarios2.setText("Tipos de usuarios registrados");
        FrmPrincipal.MenuHistorial.setText("Historial de inicios de sesión");
        FrmPrincipal.MenuClientes.setText("Clientes");
        FrmPrincipal.MenuClientes2.setText("Clientes ingresados al parqueo");
        FrmPrincipal.MenuClientes3.setText("Clientes retirados del parqueo");
        FrmPrincipal.MenuVehiculos.setText("Vehiculos");
        FrmPrincipal.MenuIngresados.setText("Vehiculos livianos");
        FrmPrincipal.MenuRetirados.setText("Vehiculos comerciales");
        FrmPrincipal.MenuVIP.setText("vehiculos VIP");
        FrmPrincipal.MenuMoto.setText("Motocicletas");
        FrmPrincipal.MenuTipoVehiculos.setText("Tipos de vehiculos");
        FrmPrincipal.MenuFinanzas.setText("Finanzas");
        FrmPrincipal.MenuTotal.setText("Ganancias totales del parqueo");
        FrmPrincipal.MenuTotal2.setText("Ganancias totales del alquiler");
        FrmPrincipal.MenuInterfaz.setText("Interfaz");
        FrmPrincipal.MenuBaseDatos.setText("Base de datos");
        FrmPrincipal.MenuAyuda.setText("Otros");
        FrmPrincipal.MenuAutores.setText("Creadores");
        FrmPrincipal.MenuReporte.setText("Reporte tecnico");
        FrmPrincipal.MenuMusica.setText("Reproduce tu musica");
        FrmPrincipal.MenuIdioma.setText("Idioma del sistema");
        FrmPrincipal.MenuSesion.setText("Cerrar sesión");
        FrmPrincipal.MenuSalir.setText("Salir");
        FrmPrincipal.BarraMenu.remove(jMenu5);
        FrmPrincipal.BarraMenu.remove(jMenu6);
        FrmPrincipal.BarraMenu.remove(jMenu7);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmIdioma dialog = new FrmIdioma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnglish;
    private javax.swing.JButton BtnEspañol;
    private javax.swing.JPanel PnlContenedor;
    private javax.swing.JLabel lbltitulo;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    // End of variables declaration//GEN-END:variables
}
