/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.ClsArduino;
import Clases.ClsConexion;
import Clases.ClsSQLQuery;
import Clases.ClsSonidos;
import Clases.ClsValidaciones;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Will Vasquez
 */
public class FrmParquear extends javax.swing.JDialog {
DefaultTableModel modelo;
private final Calendar calendar;
private int hora, minuto, segundo;
private final Timer timer;
private final ActionListener actionlistener;
private final String apagar_verde1 = "0";
private final String ensender_verde1 = "1";
private final String apagar_rojo1 = "2";
private final String ensender_rojo1 = "3";
private final String apagar_rojo2 = "4";
private final String ensender_rojo2 = "5";
private final String apagar_verde2 = "6";
private final String ensender_verde2 = "7";
private final String apagar_rojo3 = "8";
private final String ensender_rojo3 = "9";
private final String apagar_verde3 = "10";
private final String ensender_verde3 = "11";
private final String apagar_rojo4 = "12";
private final String ensender_rojo4 = "13";
private final String apagar_verde4 = "14";
private final String ensender_verde4 = "15";
private final String apagar_rojo5 = "16";
private final String ensender_rojo5 = "17";
private final String apagar_verde5 = "18";
private final String ensender_verde5 = "19";
private final String apagar_rojo6 = "20";
private final String ensender_rojo6 = "21";
private final String apagar_verde6 = "22";
private final String ensender_verde6 = "23";
private final String apagar_rojo7 = "24";
private final String ensender_rojo7 = "25";
private final String apagar_verde7 = "26";
private final String ensender_verde7 = "27";
private final String apagar_rojo8 = "28";
private final String ensender_rojo8 = "29";
private final String apagar_verde8 = "30";
private final String ensender_verde8 = "31";
    /**
     * Creates new form FrmParquear
     * @param parent
     * @param modal
     */
    public FrmParquear(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        calendar = Calendar.getInstance();
        actionlistener = new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e) {
                validarHora();
                mostrarDatos();
            }
        };
        timer = new Timer(990, actionlistener);
        initComponents();
        setTitle("Parquear vehiculos");
        setLocationRelativeTo(null);
        obtenerDatos();
        mostrarDatos();
        timer.start();
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Diseño/Parquear.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEmergente = new javax.swing.JPopupMenu();
        MenuLimpiar = new javax.swing.JMenuItem();
        panelTranslucido1 = new org.edisoncor.gui.panel.PanelTranslucido();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtplaca = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel3 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbFechaIngreso = new org.freixas.jcalendar.JCalendarCombo();
        jLabel5 = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel8 = new javax.swing.JLabel();
        txtnombres = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        txtapellidos = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel10 = new javax.swing.JLabel();
        txttelefono = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel11 = new javax.swing.JLabel();
        txtpuesto = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel12 = new javax.swing.JLabel();
        txtestado = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel13 = new javax.swing.JLabel();
        txtestadovehiculo = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVehiculos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPuestos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnConsultar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();

        MenuLimpiar.setText("Limpiar");
        MenuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLimpiarActionPerformed(evt);
            }
        });
        MenuEmergente.add(MenuLimpiar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo:");

        txtcodigo.setEditable(false);
        txtcodigo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("N° placa:");

        txtplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtplacaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo vehiculo:");

        cmbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtipoItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha ingreso:");

        cmbFechaIngreso.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora ingreso:");

        lblhora.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        lblhora.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio(Tipo vehiculo):");

        txtprecio.setDescripcion("");
        txtprecio.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombres cliente:");

        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apellidos cliente:");

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Número telefónico:");

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Puesto asignado:");

        txtpuesto.setDescripcion("");
        txtpuesto.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estado del puesto:");

        txtestado.setDescripcion("");
        txtestado.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estado del vehiculo:");

        txtestadovehiculo.setDescripcion("");
        txtestadovehiculo.setEnabled(false);

        javax.swing.GroupLayout panelTranslucido1Layout = new javax.swing.GroupLayout(panelTranslucido1);
        panelTranslucido1.setLayout(panelTranslucido1Layout);
        panelTranslucido1Layout.setHorizontalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtestadovehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtplaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelTranslucido1Layout.setVerticalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtestadovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white)); // NOI18N
        jPanel1.setOpaque(false);

        TablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaVehiculos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaVehiculos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Puestos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white)); // NOI18N
        jPanel2.setOpaque(false);

        TablaPuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaPuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPuestosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaPuestos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vehiculos registrados");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Puestos disponibles");

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Ingresar");
        BtnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnAgregar.setContentAreaFilled(false);
        BtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregar.setFocusable(false);
        BtnAgregar.setOpaque(true);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseExited(evt);
            }
        });
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnModificar.setBackground(new java.awt.Color(0, 0, 0));
        BtnModificar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Modificar");
        BtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnModificar.setContentAreaFilled(false);
        BtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnModificar.setFocusable(false);
        BtnModificar.setOpaque(true);
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnModificarMouseExited(evt);
            }
        });
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnConsultar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar.setText("Consultar");
        BtnConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnConsultar.setContentAreaFilled(false);
        BtnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConsultar.setFocusable(false);
        BtnConsultar.setOpaque(true);
        BtnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnConsultarMouseExited(evt);
            }
        });
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnEliminar.setContentAreaFilled(false);
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.setFocusable(false);
        BtnEliminar.setOpaque(true);
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseExited(evt);
            }
        });
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                    .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseEntered
        BtnAgregar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnAgregarMouseEntered

    private void BtnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseExited
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnAgregarMouseExited

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if(txtplaca.getText().isEmpty() || txtnombres.getText().isEmpty() || txtapellidos.getText().isEmpty() || txttelefono.getText().isEmpty() || txtprecio.getText().isEmpty() || txtpuesto.getText().isEmpty() || txtestado.getText().isEmpty()){
            ClsSonidos.Validar();
            JOptionPane.showMessageDialog(this, "No puedes dejar campos en blanco", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if(txtplaca.getText().length() <= 3){
            JOptionPane.showMessageDialog(this, "El numero de placa debe ser mayor a 3", "Atención", JOptionPane.CANCEL_OPTION);
        }
        else if(cmbtipo.getSelectedIndex() == -1){
            ClsSonidos.Validar();
            JOptionPane.showMessageDialog(this, "Debes seleccionar un tipo de vehiculo", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if (!ClsValidaciones.ComprobarNumeroTelefono(txttelefono.getText())) {
            JOptionPane.showMessageDialog(this, "Numero de telefono incorrecto", "AVISO", JOptionPane.CANCEL_OPTION);
            txttelefono.setText(null);
        }
        else
        {
            try {
                PreparedStatement st = cn.prepareStatement("SELECT placa FROM parquear WHERE placa = ?");
                st.setString(1, txtplaca.getText());
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    ClsSonidos.Validar();
                    JOptionPane.showMessageDialog(this, "Este numero de placa ya existe", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                st = cn.prepareStatement("SELECT nombres_cliente, apellidos_cliente FROM parquear WHERE nombres_cliente = ? AND apellidos_cliente = ?");
                st.setString(1, txtnombres.getText());
                st.setString(2, txtapellidos.getText());
                ResultSet rs2 = st.executeQuery();
                if(rs2.next()){
                    ClsSonidos.Validar();
                    JOptionPane.showMessageDialog(this, "Este cliente ya fue ingresado", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                st = cn.prepareStatement("SELECT telefono FROM parquear WHERE telefono = ?");
                st.setString(1, txttelefono.getText());
                ResultSet rs3 = st.executeQuery();
                if(rs3.next()){
                    ClsSonidos.Validar();
                    JOptionPane.showMessageDialog(this, "No pueden haber dos telefonos iguales", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = ? AND estado2 = 0");
                st.setInt(1, Integer.parseInt(txtpuesto.getText()));
                ResultSet rs6 = st.executeQuery();
                if(rs6.next()){
                    ClsSonidos.Validar();
                    JOptionPane.showMessageDialog(this, "Este puesto ya esta ocupado", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                    st = cn.prepareStatement("UPDATE puesto SET estado = 'Ocupado', estado2 = 0 WHERE puesto = ?");
                    st.setInt(1, Integer.parseInt(txtpuesto.getText()));
                    st.executeUpdate();
                    st = cn.prepareStatement("SELECT codigo_tipo FROM tipo_vehiculos WHERE nombre_tipo = ?");
                    st.setString(1, cmbtipo.getSelectedItem().toString());
                    ResultSet rs4 = st.executeQuery();
                    rs4.next();
                    String tipo_vehiculo = rs4.getString(1);
                    st = cn.prepareStatement("SELECT puesto FROM puesto WHERE puesto = ?");
                    st.setInt(1, Integer.parseInt(txtpuesto.getText()));
                    ResultSet rs5 = st.executeQuery();
                    rs5.next();
                    int puesto = rs5.getInt(1);
                    st = cn.prepareStatement("INSERT INTO parquear VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                    st.setString(1, txtplaca.getText());
                    st.setInt(2, Integer.parseInt(tipo_vehiculo));
                    java.sql.Date FechaIngreso = new java.sql.Date(cmbFechaIngreso.getDate().getTime());
                    st.setDate(3, FechaIngreso);
                    st.setString(4, lblhora.getText());
                    st.setDouble(5, Double.parseDouble(txtprecio.getText()));
                    st.setString(6, txtnombres.getText());
                    st.setString(7, txtapellidos.getText());
                    st.setString(8, txttelefono.getText());
                    st.setInt(9, puesto);
                    st.setString(10, txtestado.getText());
                    st.setString(11, "Registrado");
                    st.setInt(12, hora);
                    st.setInt(13, minuto);
                    st.setInt(14, segundo);
                    st.setInt(15, 1);
                    st.executeUpdate();
                    ClsSonidos.AgregarDatos();
                    JOptionPane.showMessageDialog(this, "Vehiculo y cliente agregado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    MostrarVehiculos();
                    MostrarPuestos();
                    FacturaEntrada();
                    limpiar();
                }
                }
                }
                }
            } catch (HeadlessException | NumberFormatException | SQLException ex) {
                Logger.getLogger(FrmPuestos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseEntered
        BtnModificar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnModificarMouseEntered

    private void BtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseExited
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnModificarMouseExited

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        if(txtplaca.getText().isEmpty() || txtnombres.getText().isEmpty() || txtapellidos.getText().isEmpty() || txttelefono.getText().isEmpty() || txtprecio.getText().isEmpty() || txtpuesto.getText().isEmpty() || txtestado.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No puedes dejar campos en blanco", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if(cmbtipo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un tipo de vehiculo", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            try {
                PreparedStatement st = cn.prepareStatement("SELECT placa FROM parquear WHERE placa = ? AND NOT codigo_parquear = ?");
                st.setString(1, txtplaca.getText());
                st.setInt(2, Integer.parseInt(txtcodigo.getText()));
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Este numero de placa ya existe", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                st = cn.prepareStatement("SELECT nombres_cliente, apellidos_cliente FROM parquear WHERE nombres_cliente = ? AND apellidos_cliente = ? AND NOT codigo_parquear = ?");
                st.setString(1, txtnombres.getText());
                st.setString(2, txtapellidos.getText());
                st.setInt(3, Integer.parseInt(txtcodigo.getText()));
                ResultSet rs2 = st.executeQuery();
                if(rs2.next()){
                    JOptionPane.showMessageDialog(this, "Este cliente ya fue ingresado", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                st = cn.prepareStatement("SELECT telefono FROM parquear WHERE telefono = ? AND NOT codigo_parquear = ?");
                st.setString(1, txttelefono.getText());
                st.setInt(2, Integer.parseInt(txtcodigo.getText()));
                ResultSet rs3 = st.executeQuery();
                if(rs3.next()){
                    JOptionPane.showMessageDialog(this, "No pueden haber dos telefonos iguales", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                    st = cn.prepareStatement("SELECT codigo_tipo FROM tipo_vehiculos WHERE nombre_tipo = ?");
                    st.setString(1, cmbtipo.getSelectedItem().toString());
                    ResultSet rs4 = st.executeQuery();
                    rs4.next();
                    String tipo_vehiculo = rs4.getString(1);
                    st = cn.prepareStatement("UPDATE parquear SET placa = ?, codigo_tipo = ?, tarifa = ?, nombres_cliente = ?, apellidos_cliente = ?, telefono = ? WHERE codigo_parquear = ?");
                    st.setString(1, txtplaca.getText());
                    st.setInt(2, Integer.parseInt(tipo_vehiculo));
                    st.setDouble(3, Double.parseDouble(txtprecio.getText()));
                    st.setString(4, txtnombres.getText());
                    st.setString(5, txtapellidos.getText());
                    st.setString(6, txttelefono.getText());
                    st.setInt(7, Integer.parseInt(txtcodigo.getText()));
                    st.executeUpdate();
                    ClsSonidos.ModificarDatos();
                    JOptionPane.showMessageDialog(this, "Vehiculo y cliente modificado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    MostrarVehiculos();
                    limpiar();
                }
                }
                }
            } catch (SQLException | NumberFormatException | HeadlessException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConsultarMouseEntered
        BtnConsultar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnConsultarMouseEntered

    private void BtnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConsultarMouseExited
        BtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnConsultarMouseExited

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        MostrarVehiculos();
    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void BtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseEntered
        BtnEliminar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnEliminarMouseEntered

    private void BtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseExited
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnEliminarMouseExited

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if("".equals(txtcodigo.getText())) {
            JOptionPane.showMessageDialog(this, "¡Debe realizar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            try{
            PreparedStatement st = cn.prepareStatement("DELETE FROM parquear WHERE codigo_parquear = ?");
            st.setInt(1, Integer.parseInt(txtcodigo.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar?", "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(eliminar == 0){
                st.execute();
                st = cn.prepareStatement("UPDATE puesto SET estado = 'Libre', estado2 = 1 WHERE puesto = ?");
                st.setInt(1, Integer.parseInt(txtpuesto.getText()));
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Datos eliminados");
                MostrarVehiculos();
                MostrarPuestos();
                limpiar();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
            }catch(SQLException | NumberFormatException | HeadlessException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ClsSonidos.AbrirVentana();
        CargarTipo();
        MostrarPuestos();
        cmbtipo.setSelectedIndex(-1);
        txtestadovehiculo.setText("Sin registrar");
    }//GEN-LAST:event_formWindowOpened

    private void cmbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtipoItemStateChanged
        if(cmbtipo.getSelectedIndex() >= 0){
            try {
            PreparedStatement st = cn.prepareStatement("SELECT CONVERT(decimal(7,2), tarifa_tipo, 0) FROM tipo_vehiculos WHERE nombre_tipo = ?");
            st.setString(1, cmbtipo.getSelectedItem().toString());
            ResultSet rs = st.executeQuery();
            rs.next();
            String Precio = rs.getString(1);
            txtprecio.setText(Precio);
            }catch(SQLException e){
                System.out.println(e);
            }
        }
        else{
            txtprecio.setText(null);
        }
    }//GEN-LAST:event_cmbtipoItemStateChanged

    private void TablaPuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPuestosMouseClicked
        txtpuesto.setText(TablaPuestos.getValueAt(TablaPuestos.getSelectedRow(), 0).toString());
        txtestado.setText(TablaPuestos.getValueAt(TablaPuestos.getSelectedRow(), 1).toString());
        try {
            PreparedStatement st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 1");
            ResultSet rs = st.executeQuery();
            if(rs.next()){
            int EstadoPuesto = rs.getInt(1);
            if(EstadoPuesto == 1){
                ClsArduino.EnviarDatos(apagar_rojo1);
                ClsArduino.EnviarDatos(ensender_verde1);
            }
            else if(EstadoPuesto == 0){
                ClsArduino.EnviarDatos(apagar_verde1);
                ClsArduino.EnviarDatos(ensender_rojo1);
            }
            }
        } catch (NumberFormatException | SQLException e) {JOptionPane.showMessageDialog(this,"Excepción SQL: " + e, "Atención", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_TablaPuestosMouseClicked

    private void TablaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVehiculosMouseClicked
        try {
        txtcodigo.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 0).toString());
        txtplaca.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 1).toString());
        cmbtipo.setSelectedItem(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 2).toString());
        SimpleDateFormat Formateador = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date fechaIngreso = Formateador.parse(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 3).toString());
        cmbFechaIngreso.setDate(fechaIngreso);
        lblhora.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 4).toString());
        txtprecio.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 5).toString());
        txtnombres.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 6).toString());
        txtapellidos.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 7).toString());
        txttelefono.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 8).toString());
        txtpuesto.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 9).toString());
        txtestado.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 10).toString());
        txtestadovehiculo.setText(TablaVehiculos.getValueAt(TablaVehiculos.getSelectedRow(), 11).toString());
        }catch(ParseException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_TablaVehiculosMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ClsSonidos.CerrarVentana();
    }//GEN-LAST:event_formWindowClosing

    private void txtplacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplacaKeyTyped
        if (txtplaca.getText().length() == 6) {
            evt.consume();
        }
        else if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtplacaKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        if (txttelefono.getText().length() == 9) {
            evt.consume();
        }
        else if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '-')) {
            evt.consume();
        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        if (txtapellidos.getText().length() >= 50) {
            evt.consume();
        }
        char car = evt.getKeyChar();    
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        if (txtnombres.getText().length() >= 50) {
            evt.consume();
        }
        char car = evt.getKeyChar();    
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getButton() == 3)
        {
            MenuEmergente.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void MenuLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLimpiarActionPerformed
        limpiar();
        TablaVehiculos.setModel(new DefaultTableModel());
    }//GEN-LAST:event_MenuLimpiarActionPerformed

    void MostrarVehiculos()
    {
    modelo= new DefaultTableModel();
    modelo.addColumn("Codigo");
    modelo.addColumn("N° placa");
    modelo.addColumn("Tipo vehiculo");
    modelo.addColumn("Fecha ingreso");
    modelo.addColumn("Hora ingreso");
    modelo.addColumn("Precio");
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Telefono");
    modelo.addColumn("Puesto asignado");
    modelo.addColumn("Estado del puesto");
    modelo.addColumn("Estado del vehiculo");
    TablaVehiculos.setModel(modelo);
    String sql="SELECT codigo_parquear, placa, nombre_tipo, CONVERT(VARCHAR(10), fecha_ingreso, 105), hora_ingreso, CONVERT(decimal(7,2), tarifa, 0), nombres_cliente, apellidos_cliente, telefono, puesto, estado, estado_vehiculo FROM parquear p, tipo_vehiculos v WHERE p.codigo_tipo=v.codigo_tipo";
    String []datos = new String [12];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                modelo.addRow(datos);
            }
            TablaVehiculos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(FrmParquear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void MostrarPuestos()
    {
    modelo= new DefaultTableModel();
    modelo.addColumn("N° puesto");
    modelo.addColumn("Estado");
    TablaPuestos.setModel(modelo);
    String sql="SELECT * FROM puesto";
    String []datos = new String [2];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                modelo.addRow(datos);
            }
            TablaPuestos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(FrmParquear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CargarTipo() 
    {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nombre_tipo FROM tipo_vehiculos ORDER BY nombre_tipo");
            cmbtipo.removeAllItems();
            while(rs.next())
            {
                cmbtipo.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmParquear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void limpiar(){
        txtcodigo.setText(null);
        txtplaca.setText(null);
        cmbtipo.setSelectedIndex(-1);
        cmbFechaIngreso.setDate(new java.util.Date());
        mostrarDatos();
        txtprecio.setText(null);
        txtnombres.setText(null);
        txtapellidos.setText(null);
        txttelefono.setText(null);
        txtpuesto.setText(null);
        txtestado.setText(null);
        txtestadovehiculo.setText("Sin registrar");
        txtestado.setText("Ocupado");
    }
    
    private void obtenerDatos(){
        hora = calendar.get(Calendar.HOUR_OF_DAY);
        minuto = calendar.get(Calendar.MINUTE);
        segundo = calendar.get(Calendar.SECOND);
    }
    private void mostrarDatos(){
        lblhora.setText(hora + " : " + minuto + " : " + segundo);
    }
    
    private void validarHora(){
        if(segundo == 59){
            minuto++;
            segundo = 0;
            if(minuto == 59){
                hora++;
                minuto = 0;
                if(hora == 23){
                    hora = 0;
                }
            }
        }else{
                segundo++;
            }
        }
    
    void FacturaEntrada(){
        String path = null;
        try {
            String Codigo = txtplaca.getText();
            path = getClass().getResource("/Reportes/TicketIngreso.jasper").getPath();
            path = URLDecoder.decode(path, "UTF-8");
            Map parametros = new HashMap();
            parametros.put("Codigo", Codigo);
            parametros.put("Nombres", ClsSQLQuery.ProNombresUsuario);
            parametros.put("Apellidos", ClsSQLQuery.ProApellidosUsuario);
            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
            JasperViewer visor = new JasperViewer(imprimir, false);
            setModal(false);
            visor.setTitle("Factura de entrada");
            visor.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
            visor.setVisible(true);
            setModal(true); 
        } catch (UnsupportedEncodingException | JRException e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmParquear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmParquear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmParquear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmParquear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmParquear dialog = new FrmParquear(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JPopupMenu MenuEmergente;
    private javax.swing.JMenuItem MenuLimpiar;
    private javax.swing.JTable TablaPuestos;
    private javax.swing.JTable TablaVehiculos;
    private org.freixas.jcalendar.JCalendarCombo cmbFechaIngreso;
    private javax.swing.JComboBox cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblhora;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido1;
    private org.edisoncor.gui.textField.TextFieldRound txtapellidos;
    private java.awt.TextField txtcodigo;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtestado;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtestadovehiculo;
    private org.edisoncor.gui.textField.TextFieldRound txtnombres;
    private org.edisoncor.gui.textField.TextFieldRound txtplaca;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtprecio;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtpuesto;
    private org.edisoncor.gui.textField.TextFieldRound txttelefono;
    // End of variables declaration//GEN-END:variables
ClsConexion cc= new ClsConexion();
Connection cn= cc.conectar();
}
