/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;
import Clases.ClsArduino;
import Clases.ClsConexion;
import Clases.ClsSonidos;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Will Vasquez
 */
public class FrmPuestos extends javax.swing.JDialog {
DefaultTableModel modelo;
public static String puesto1on = "3";
public static String puesto1off = "4";
public static String puesto2on = "5";
public static String puesto2off = "6";
public static String puesto3on = "7";
public static String puesto3off = "8";
public static String puesto4on = "9";
public static String puesto4off = "10";
public static String puesto5on = "11";
public static String puesto5off = "12";
public static String puesto6on = "13";
public static String puesto6off = "14";
public static String puesto7on = "15";
public static String puesto7off = "16";
public static String puesto8on = "17";
public static String puesto8off = "18";
public static String apagar = "2";

    /**
     * Creates new form FrmPuestos
     * @param parent
     * @param modal
     */
    public FrmPuestos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Puestos del parqueadero");
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Diseño/Puestos.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTranslucido1 = new org.edisoncor.gui.panel.PanelTranslucido();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox();
        BtnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        BtnAgregar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N° puesto:");

        txtcodigo.setEditable(false);
        txtcodigo.setEnabled(false);
        txtcodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estado:");

        cmbestado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cmbestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libre", "Reservado" }));
        cmbestado.setSelectedIndex(-1);

        javax.swing.GroupLayout panelTranslucido1Layout = new javax.swing.GroupLayout(panelTranslucido1);
        panelTranslucido1.setLayout(panelTranslucido1Layout);
        panelTranslucido1Layout.setHorizontalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbestado, 0, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTranslucido1Layout.setVerticalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnNuevo.setBackground(new java.awt.Color(0, 0, 0));
        BtnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnNuevo.setContentAreaFilled(false);
        BtnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNuevo.setFocusable(false);
        BtnNuevo.setOpaque(true);
        BtnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnNuevoMouseExited(evt);
            }
        });
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnAgregar.setContentAreaFilled(false);
        BtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregar.setFocusable(false);
        BtnAgregar.setOpaque(true);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseExited(evt);
            }
        });
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnModificar.setBackground(new java.awt.Color(0, 0, 0));
        BtnModificar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Modificar");
        BtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnModificar.setContentAreaFilled(false);
        BtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnModificar.setFocusable(false);
        BtnModificar.setOpaque(true);
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnModificarMouseExited(evt);
            }
        });
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnEliminar.setContentAreaFilled(false);
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.setFocusable(false);
        BtnEliminar.setOpaque(true);
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseExited(evt);
            }
        });
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelCurves1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCurves1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNuevoMouseEntered
        BtnNuevo.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnNuevoMouseEntered

    private void BtnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNuevoMouseExited
        BtnNuevo.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnNuevoMouseExited

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        try {
            PreparedStatement st = cn.prepareStatement("SELECT MAX(puesto) + 1 FROM puesto");
            ResultSet rs = st.executeQuery();
            rs.next();
            String Puesto = rs.getString(1);
            txtcodigo.setText(Puesto);
            MostrarDatos();
        } catch (SQLException | NumberFormatException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseEntered
        BtnAgregar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnAgregarMouseEntered

    private void BtnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseExited
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnAgregarMouseExited

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if(cmbestado.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Debe establecer el estado del puesto", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
        try {
            if(cmbestado.getSelectedItem().equals("Libre")){
            PreparedStatement st = cn.prepareStatement("INSERT INTO puesto VALUES(?, ?, 1)");
            st.setInt(1, Integer.parseInt(txtcodigo.getText()));
            st.setString(2, cmbestado.getSelectedItem().toString());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Puesto agregado", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            MostrarDatos();
            txtcodigo.setText(null);
            cmbestado.setSelectedIndex(-1);
            }
            else if(cmbestado.getSelectedItem().equals("Reservado")){
                PreparedStatement st = cn.prepareStatement("INSERT INTO puesto VALUES(?, ?, 2)");
                st.setInt(1, Integer.parseInt(txtcodigo.getText()));
                st.setString(2, cmbestado.getSelectedItem().toString());
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Puesto agregado", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                MostrarDatos();
                txtcodigo.setText(null);
                cmbestado.setSelectedIndex(-1);
            }
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Solo puedes agregar puestos de forma ascendente", "AVISO", JOptionPane.CANCEL_OPTION);
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseEntered
        BtnModificar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnModificarMouseEntered

    private void BtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseExited
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnModificarMouseExited

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        if(cmbestado.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Debe establecer el estado del puesto", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if(txtcodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un puesto a modificar", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            try {
                PreparedStatement st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = ? AND estado2 = 0");
                st.setInt(1, Integer.parseInt(txtcodigo.getText()));
                ResultSet rs6 = st.executeQuery();
                if(rs6.next()){
                    JOptionPane.showMessageDialog(this, "No puedes modificar este puesto", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                st = cn.prepareStatement("UPDATE puesto SET estado = ? WHERE puesto = ?");
                st.setString(1, cmbestado.getSelectedItem().toString());
                st.setInt(2, Integer.parseInt(txtcodigo.getText()));
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Puesto modificado", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                MostrarDatos();
                txtcodigo.setText(null);
                cmbestado.setSelectedIndex(-1);
                }
            } catch (SQLException | HeadlessException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseEntered
        BtnEliminar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnEliminarMouseEntered

    private void BtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseExited
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnEliminarMouseExited

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if("".equals(txtcodigo.getText())) {
            JOptionPane.showMessageDialog(this, "¡Debe realizar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            try{
            PreparedStatement st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = ? AND estado2 = 0");
            st.setInt(1, Integer.parseInt(txtcodigo.getText()));
            ResultSet rs6 = st.executeQuery();
            if(rs6.next()){
                JOptionPane.showMessageDialog(this, "No puedes eliminar este puesto", "AVISO", JOptionPane.CANCEL_OPTION);
            }
            else{
            st = cn.prepareStatement("SELECT MAX(puesto) FROM puesto");
            ResultSet rs = st.executeQuery();
            rs.next();
            String Puesto = rs.getString(1);
            st = cn.prepareStatement("DELETE FROM puesto WHERE puesto = ?");
            st.setInt(1, Integer.parseInt(txtcodigo.getText()));
            if(Integer.parseInt(txtcodigo.getText()) < Integer.parseInt(Puesto)){
                JOptionPane.showMessageDialog(this, "Solo puedes eliminar los puestos de forma descendente", "AVISO", JOptionPane.CANCEL_OPTION);
            }
            else{
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar?", "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(eliminar == 0){
                st.execute();
                JOptionPane.showMessageDialog(this, "Datos eliminados");
                MostrarDatos();
                txtcodigo.setText(null);
                cmbestado.setSelectedIndex(-1);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
            }
            }
            }catch(SQLException | NumberFormatException | HeadlessException e){
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ClsSonidos.AbrirVentana();
        MostrarDatos();
    }//GEN-LAST:event_formWindowOpened

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        try{
        txtcodigo.setText(Tabla.getValueAt(Tabla.getSelectedRow(), 0).toString());
        cmbestado.setSelectedItem(Tabla.getValueAt(Tabla.getSelectedRow(), 1).toString());
        PreparedStatement st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 1");
        ResultSet rs = st.executeQuery();
        rs.next();
        int puesto1 = rs.getInt(1);
        if(puesto1 == 1){
            ClsArduino.EnviarDatos(puesto1on);
        }
        else if(puesto1 == 0){
            ClsArduino.EnviarDatos(puesto1off);
        }
        else{
            st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 2");
            ResultSet rs2 = st.executeQuery();
            rs2.next();
            int puesto2 = rs2.getInt(1);
            if(puesto2 == 1){
                ClsArduino.EnviarDatos(puesto2on);
            }
            else if(puesto2 == 0){
                ClsArduino.EnviarDatos(puesto2off);
            }
            else{
                st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 3");
                ResultSet rs3 = st.executeQuery();
                rs3.next();
                int puesto3 = rs3.getInt(1);
                if(puesto3 == 1){
                    ClsArduino.EnviarDatos(puesto3on);
                }
                else if(puesto3 == 0){
                    ClsArduino.EnviarDatos(puesto3off);
                }
                else{
                    st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 4");
                    ResultSet rs4 = st.executeQuery();
                    rs4.next();
                    int puesto4 = rs4.getInt(1);
                    if(puesto4 == 1){
                        ClsArduino.EnviarDatos(puesto4on);
                    }
                    else if(puesto4 == 0){
                        ClsArduino.EnviarDatos(puesto4off);
                    }
                    else{
                        st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 5");
                        ResultSet rs5 = st.executeQuery();
                        rs5.next();
                        int puesto5 = rs5.getInt(1);
                        if(puesto5 == 1){
                            ClsArduino.EnviarDatos(puesto5on);
                        }
                        else if(puesto5 == 0){
                            ClsArduino.EnviarDatos(puesto5off);
                        }
                        else{
                            st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 6");
                            ResultSet rs6 = st.executeQuery();
                            rs6.next();
                            int puesto6 = rs6.getInt(1);
                            if(puesto6 == 1){
                                ClsArduino.EnviarDatos(puesto6on);
                            }
                            else if(puesto6 == 0){
                                ClsArduino.EnviarDatos(puesto6off);
                            }
                            else{
                                st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 7");
                                ResultSet rs7 = st.executeQuery();
                                rs7.next();
                                int puesto7 = rs7.getInt(1);
                                if(puesto7 == 1){
                                    ClsArduino.EnviarDatos(puesto7on);
                                }
                                else if(puesto7 == 0){
                                    ClsArduino.EnviarDatos(puesto7off);
                                }
                                else{
                                    st = cn.prepareStatement("SELECT estado2 FROM puesto WHERE puesto = 8 AND");
                                    ResultSet rs8 = st.executeQuery();
                                    rs8.next();
                                    int puesto8 = rs8.getInt(1);
                                    if(puesto8 == 1){
                                        ClsArduino.EnviarDatos(puesto8on);
                                    }
                                    else if(puesto8 == 2){
                                        ClsArduino.EnviarDatos(puesto8off);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        }catch(SQLException e){
            Logger.getLogger(FrmPuestos.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ClsSonidos.CerrarVentana();
        ClsArduino.EnviarDatos(apagar);
    }//GEN-LAST:event_formWindowClosing

    public void MostrarDatos(){
    modelo= new DefaultTableModel();
    modelo.addColumn("Puesto");
    modelo.addColumn("Estado");
    Tabla.setModel(modelo);
    String sql="SELECT * FROM puesto";
    String []datos = new String [2];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                modelo.addRow(datos);
            }
            Tabla.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(FrmPuestos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPuestos dialog = new FrmPuestos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JTable Tabla;
    private javax.swing.JComboBox cmbestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido1;
    private java.awt.TextField txtcodigo;
    // End of variables declaration//GEN-END:variables
ClsConexion cc= new ClsConexion();
Connection cn= cc.conectar();
}
