/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.ClsConexion;
import Clases.ClsSQLQuery;
import Clases.ClsSonidos;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Will Vasquez
 */
public class FrmRetirar extends javax.swing.JDialog {
DefaultTableModel modelo;
private final Calendar calendar, calendar2;
private int hora, minuto, segundo;
private final Timer timer;
private final ActionListener actionlistener;
Double total;

    /**
     * Creates new form FrmRetirar
     * @param parent
     * @param modal
     */
    public FrmRetirar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        calendar = Calendar.getInstance();
        calendar2 = Calendar.getInstance();
        actionlistener = new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e) {
                validarHora();
                mostrarDatos();
            }
        };
        timer = new Timer(990, actionlistener);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Retiro de vehiculos");
        obtenerDatos();
        mostrarDatos();
        timer.start();
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Diseño/Retirar.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTranslucido1 = new org.edisoncor.gui.panel.PanelTranslucido();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbFechaIngreso = new org.freixas.jcalendar.JCalendarCombo();
        jLabel5 = new javax.swing.JLabel();
        lblhoraingreso = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtplaca = new org.edisoncor.gui.textField.TextFieldRectBackground();
        txttarifa = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel7 = new javax.swing.JLabel();
        txtnombres = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel8 = new javax.swing.JLabel();
        txtapellidos = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel10 = new javax.swing.JLabel();
        txttelefono = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel11 = new javax.swing.JLabel();
        cmbFechaSalida = new org.freixas.jcalendar.JCalendarCombo();
        jLabel12 = new javax.swing.JLabel();
        lblhorasalida = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttiempo = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel15 = new javax.swing.JLabel();
        txtestadovehiculo = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel16 = new javax.swing.JLabel();
        txtpuesto = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel17 = new javax.swing.JLabel();
        txtestadopuesto = new org.edisoncor.gui.textField.TextFieldRectBackground();
        lblhoras = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDentro = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaFuera = new javax.swing.JTable();
        BtnRetirar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo:");

        txtcodigo.setEditable(false);
        txtcodigo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Placa:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo vehiculo:");

        cmbtipo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha ingreso:");

        cmbFechaIngreso.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora ingreso:");

        lblhoraingreso.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        lblhoraingreso.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tarifa:");

        txtplaca.setDescripcion("");
        txtplaca.setEnabled(false);

        txttarifa.setDescripcion("");
        txttarifa.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombres cliente:");

        txtnombres.setDescripcion("");
        txtnombres.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apellidos cliente:");

        txtapellidos.setDescripcion("");
        txtapellidos.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Número telefónico:");

        txttelefono.setDescripcion("");
        txttelefono.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha salida:");

        cmbFechaSalida.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hora salida:");

        lblhorasalida.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        lblhorasalida.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Min. transcurridos:");

        txttiempo.setDescripcion("");
        txttiempo.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Monto a pagar:");

        txttotal.setDescripcion("");
        txttotal.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Estado del vehiculo:");

        txtestadovehiculo.setDescripcion("");
        txtestadovehiculo.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Puesto asignado:");

        txtpuesto.setDescripcion("");
        txtpuesto.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Estado del puesto:");

        txtestadopuesto.setDescripcion("");
        txtestadopuesto.setEnabled(false);

        lblhoras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblhoras.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTranslucido1Layout = new javax.swing.GroupLayout(panelTranslucido1);
        panelTranslucido1.setLayout(panelTranslucido1Layout);
        panelTranslucido1Layout.setHorizontalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(56, 56, 56)
                        .addComponent(cmbFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblhoraingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtnombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttarifa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                                .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(81, 81, 81)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtestadopuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtestadovehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(25, 25, 25)
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblhorasalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                                .addComponent(txttiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblhoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelTranslucido1Layout.setVerticalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhoraingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhorasalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txttiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtestadovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtestadopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Vehiculos dentro del parqueo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white)); // NOI18N
        jPanel1.setOpaque(false);

        TablaDentro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDentro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TablaDentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDentroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDentro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Vehiculos fuera del parqueo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white)); // NOI18N
        jPanel2.setOpaque(false);

        TablaFuera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaFuera.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TablaFuera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFueraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaFuera);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnRetirar.setBackground(new java.awt.Color(0, 0, 0));
        BtnRetirar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetirar.setText("Retirar vehiculo");
        BtnRetirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnRetirar.setContentAreaFilled(false);
        BtnRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetirar.setFocusable(false);
        BtnRetirar.setOpaque(true);
        BtnRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRetirarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRetirarMouseExited(evt);
            }
        });
        BtnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetirarActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        BtnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnLimpiar.setContentAreaFilled(false);
        BtnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiar.setFocusable(false);
        BtnLimpiar.setOpaque(true);
        BtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLimpiarMouseExited(evt);
            }
        });
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetirarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRetirarMouseEntered
        BtnRetirar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnRetirarMouseEntered

    private void BtnRetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRetirarMouseExited
        BtnRetirar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnRetirarMouseExited

    private void BtnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetirarActionPerformed
        if(txtcodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un vehiculo para llevar a cabo el retiro", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else
        try {
            PreparedStatement st = cn.prepareStatement("SELECT placa FROM retirar_vehiculo WHERE placa = ?");
            st.setString(1, txtplaca.getText());
            ResultSet rs = st.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "No puedes retirar un vehiculo que esta fuera del parqueo", "AVISO", JOptionPane.CANCEL_OPTION);
            }
            else{
                st = cn.prepareStatement("SELECT estado2 FROM parquear WHERE codigo_parquear = ? AND estado2 = 2");
                st.setInt(1,Integer.parseInt(txtcodigo.getText()));
                ResultSet rs4 = st.executeQuery();
                if(rs4.next()){
                    JOptionPane.showMessageDialog(this, "No puede eliminar este cliente porque esta usando el servicio de alquiler", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                Object [] opciones ={"Aceptar", "Cancelar"};
                DecimalFormat df = new DecimalFormat("0.00");
                if (JOptionPane.showOptionDialog(null, "El monto a pagar es (US$) " + df.format(total) + "\n¿Llevar a cabo la cancelación?", "AVISO", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION, null, opciones, "Aceptar") == JOptionPane.YES_OPTION) {
                st = cn.prepareStatement("INSERT INTO retirar_vehiculo VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                st.setString(1, txtplaca.getText());
                st.setString(2, cmbtipo.getSelectedItem().toString());
                java.sql.Date FechaIngreso = new java.sql.Date(cmbFechaIngreso.getDate().getTime());
                st.setDate(3, FechaIngreso);
                st.setString(4, lblhoraingreso.getText());
                st.setDouble(5, Double.parseDouble(txttarifa.getText()));
                st.setString(6, txtnombres.getText());
                st.setString(7, txtapellidos.getText());
                st.setString(8, txttelefono.getText());
                java.sql.Date FechaSalida = new java.sql.Date(cmbFechaSalida.getDate().getTime());
                st.setDate(9, FechaSalida);
                st.setString(10, lblhorasalida.getText());
                st.setInt(11, Integer.parseInt(txttiempo.getText()));
                st.setDouble(12, Double.parseDouble(txttotal.getText()));
                st.setString(13, txtestadovehiculo.getText());
                st.setInt(14, Integer.parseInt(txtpuesto.getText()));
                st.setString(15, txtestadopuesto.getText());
                st.executeUpdate();
                st = cn.prepareStatement("DELETE FROM parquear WHERE codigo_parquear = ?");
                st.setInt(1, Integer.parseInt(txtcodigo.getText()));
                st.execute();
                st = cn.prepareStatement("UPDATE puesto SET estado = 'Libre', estado2 = 1 WHERE puesto = ?");
                st.setInt(1, Integer.parseInt(txtpuesto.getText()));
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Vehiculo retirado con exito", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                MostrarVehiculos();
                MostrarVehiculosRetirados();
                FacturaSalida();
                limpiar();
                }
                else{
                    JOptionPane.showMessageDialog(this, "!No podras retirar tu vehiculo si no pagas¡", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                }
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            Logger.getLogger(FrmParquear.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_BtnRetirarActionPerformed

    private void BtnLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarMouseEntered
        BtnLimpiar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnLimpiarMouseEntered

    private void BtnLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarMouseExited
        BtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnLimpiarMouseExited

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        limpiar();
        TablaFuera.setModel(new DefaultTableModel());
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void TablaDentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDentroMouseClicked
        try {
            txtcodigo.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 0).toString());
            txtplaca.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 1).toString());
            cmbtipo.setSelectedItem(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 2).toString());
            SimpleDateFormat Formateador = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date fechaIngreso = Formateador.parse(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 3).toString());
            cmbFechaIngreso.setDate(fechaIngreso);
            lblhoraingreso.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 4).toString());
            txttarifa.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 5).toString());
            txtnombres.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 6).toString());
            txtapellidos.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 7).toString());
            txttelefono.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 8).toString());
            PreparedStatement st = cn.prepareStatement("SELECT horas, minutos, segundos FROM parquear WHERE placa = ?");
            st.setString(1, txtplaca.getText());
            ResultSet rs = st.executeQuery();
            rs.next();
            int horas = rs.getInt(1);
            int minutos = rs.getInt(2);
            int segundos = rs.getInt(3);
            calendar.set(0000, 00, 00, horas, minutos, segundos);
	    calendar2.set(0000, 00, 00, hora, minuto, segundo);
            NumberFormat df = new DecimalFormat("0.00");
            long milis1 = calendar.getTimeInMillis();
	    long milis2 = calendar2.getTimeInMillis();
            long diff = milis2 - milis1;
            long diffMinutes = diff / (60 * 1000);
            long diffHours = diff / (60 * 60 * 1000);
            txttiempo.setText(String.valueOf(diffMinutes));
            total = ((Double.parseDouble(txttiempo.getText()) / 100) * Double.parseDouble(txttarifa.getText()));
            txttotal.setText(String.valueOf(df.format(total)));
            lblhoras.setText(String.valueOf(diffHours)+ " Horas");
            txtestadovehiculo.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 9).toString());
            txtpuesto.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 10).toString());
            txtestadopuesto.setText(TablaDentro.getValueAt(TablaDentro.getSelectedRow(), 11).toString());
        } catch (NumberFormatException | SQLException | ParseException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_TablaDentroMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ClsSonidos.AbrirVentana();
        MostrarVehiculos();
        CargarTipo();
        cmbtipo.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ClsSonidos.CerrarVentana();
    }//GEN-LAST:event_formWindowClosing

    private void TablaFueraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFueraMouseClicked
        try {
            txtcodigo.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 0).toString());
            txtplaca.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 1).toString());
            cmbtipo.setSelectedItem(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 2).toString());
            SimpleDateFormat Formateador = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date fechaIngreso = Formateador.parse(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 3).toString());
            cmbFechaIngreso.setDate(fechaIngreso);
            lblhoraingreso.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 4).toString());
            txttarifa.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 5).toString());
            txtnombres.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 6).toString());
            txtapellidos.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 7).toString());
            txttelefono.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 8).toString());
            java.util.Date fechaSalida = Formateador.parse(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 9).toString());
            cmbFechaSalida.setDate(fechaSalida);
            lblhorasalida.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 10).toString());
            txttiempo.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 11).toString());
            txttotal.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 12).toString());
            txtestadovehiculo.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 13).toString());
            txtpuesto.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 14).toString());
            txtestadopuesto.setText(TablaFuera.getValueAt(TablaFuera.getSelectedRow(), 15).toString());
        } catch (ParseException e) {System.out.println(e);}
    }//GEN-LAST:event_TablaFueraMouseClicked

    void MostrarVehiculos()
    {
    modelo= new DefaultTableModel();
    modelo.addColumn("Codigo");
    modelo.addColumn("N° placa");
    modelo.addColumn("Tipo vehiculo");
    modelo.addColumn("Fecha ingreso");
    modelo.addColumn("Hora ingreso");
    modelo.addColumn("Precio");
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Telefono");
    modelo.addColumn("Estado del vehiculo");
    modelo.addColumn("Puesto asignado");
    modelo.addColumn("Estado del puesto");
    TablaDentro.setModel(modelo);
    String sql="SELECT codigo_parquear, placa, nombre_tipo, CONVERT(VARCHAR(10), fecha_ingreso, 105), hora_ingreso, CONVERT(decimal(7,2), tarifa, 0), nombres_cliente, apellidos_cliente, telefono, estado_vehiculo, puesto, estado FROM parquear p, tipo_vehiculos v WHERE p.codigo_tipo=v.codigo_tipo";
    String []datos = new String [12];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                modelo.addRow(datos);
            }
            TablaDentro.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(FrmParquear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void MostrarVehiculosRetirados()
    {
    modelo= new DefaultTableModel();
    modelo.addColumn("Codigo");
    modelo.addColumn("N° placa");
    modelo.addColumn("Tipo vehiculo");
    modelo.addColumn("Fecha ingreso");
    modelo.addColumn("Hora ingreso");
    modelo.addColumn("Precio");
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Telefono");
    modelo.addColumn("Fecha salida");
    modelo.addColumn("Hora salida");
    modelo.addColumn("Min. transcurridos");
    modelo.addColumn("Monto total");
    modelo.addColumn("Estado del vehiculo");
    modelo.addColumn("Puesto asignado");
    modelo.addColumn("Estado del puesto");
    TablaFuera.setModel(modelo);
    String sql="SELECT codigo_retiro, placa, tipo_vehiculo, CONVERT(VARCHAR(10), fecha_inicio, 105), hora_ingreso, CONVERT(decimal(7,2), tarifa, 0), nombres_cliente, apellidos_cliente, telefono, CONVERT(VARCHAR(10), fecha_salida, 105), hora_salida, horas_transcurridas, CONVERT(decimal(7,2), monto_total, 0), estado_vehiculo, numero_puesto, estado_puesto FROM retirar_vehiculo";
    String []datos = new String [16];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                datos[12]=rs.getString(13);
                datos[13]=rs.getString(14);
                datos[14]=rs.getString(15);
                datos[15]=rs.getString(16);
                modelo.addRow(datos);
            }
            TablaFuera.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(FrmParquear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CargarTipo() 
    {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nombre_tipo FROM tipo_vehiculos ORDER BY nombre_tipo");
            cmbtipo.removeAllItems();
            while(rs.next())
            {
                cmbtipo.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmParquear.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void obtenerDatos(){
        hora = calendar.get(Calendar.HOUR_OF_DAY);
        minuto = calendar.get(Calendar.MINUTE);
        segundo = calendar.get(Calendar.SECOND);
    }
    private void mostrarDatos(){
        lblhorasalida.setText(hora + " : " + minuto + " : " + segundo);
    }
    
    private void validarHora(){
        if(segundo == 59){
            minuto++;
            segundo = 0;
            if(minuto == 59){
                hora++;
                minuto = 0;
                if(hora == 23){
                    hora = 0;
                }
            }
        }else{
                segundo++;
            }
        }
    
    void limpiar(){
        txtcodigo.setText(null);
        txtplaca.setText(null);
        cmbtipo.setSelectedIndex(-1);
        cmbFechaIngreso.setDate(new java.util.Date());
        cmbFechaSalida.setDate(new java.util.Date());
        lblhoraingreso.setText(null);
        txttarifa.setText(null);
        txtnombres.setText(null);
        txtapellidos.setText(null);
        txttelefono.setText(null);
        lblhorasalida.setText(null);
        mostrarDatos();
        txttiempo.setText(null);
        txttotal.setText(null);
        txtestadopuesto.setText(null);
        txtestadovehiculo.setText(null);
        txtpuesto.setText(null);
        lblhoras.setText(null);
    }
    
    void FacturaSalida(){
        String path = null;
        try {
            String Codigo = txtplaca.getText();
            path = getClass().getResource("/Reportes/TicketRetiro.jasper").getPath();
            path = URLDecoder.decode(path, "UTF-8");
            Map parametros = new HashMap();
            parametros.put("Codigo", Codigo);
            parametros.put("Nombres", ClsSQLQuery.ProNombresUsuario);
            parametros.put("Apellidos", ClsSQLQuery.ProApellidosUsuario);
            parametros.put("Usuario", ClsSQLQuery.ProNombreUsuario);
            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
            JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
            JasperViewer visor = new JasperViewer(imprimir, false);
            setModal(false);
            visor.setTitle("Factura de salida");
            visor.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
            visor.setVisible(true);
            setModal(true); 
        } catch (UnsupportedEncodingException | JRException e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRetirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRetirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRetirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRetirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRetirar dialog = new FrmRetirar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnRetirar;
    private javax.swing.JTable TablaDentro;
    private javax.swing.JTable TablaFuera;
    private org.freixas.jcalendar.JCalendarCombo cmbFechaIngreso;
    private org.freixas.jcalendar.JCalendarCombo cmbFechaSalida;
    private javax.swing.JComboBox cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblhoraingreso;
    private javax.swing.JLabel lblhoras;
    private javax.swing.JLabel lblhorasalida;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido1;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtapellidos;
    private java.awt.TextField txtcodigo;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtestadopuesto;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtestadovehiculo;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtnombres;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtplaca;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtpuesto;
    private org.edisoncor.gui.textField.TextFieldRectBackground txttarifa;
    private org.edisoncor.gui.textField.TextFieldRectBackground txttelefono;
    private org.edisoncor.gui.textField.TextFieldRectBackground txttiempo;
    private org.edisoncor.gui.textField.TextFieldRectBackground txttotal;
    // End of variables declaration//GEN-END:variables
ClsConexion cc= new ClsConexion();
Connection cn= cc.conectar();
}
