/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.ClsConexion;
import Clases.ClsIconos;
import Clases.ClsSQLQuery;
import Clases.ClsSonidos;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Will Vasquez
 */
public class FrmSesión extends javax.swing.JFrame {
private final Calendar calendar;
private int hora, minuto, segundo;
private final Timer timer;
private final ActionListener actionlistener;
    /**
     * Creates new form FrmSesión
     */
    public FrmSesión() {
        calendar = Calendar.getInstance();
        actionlistener = new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e) {
                validarHora();
                mostrarDatos();
            }
        };
        timer = new Timer(990, actionlistener);
        initComponents();
        obtenerDatos();
        mostrarDatos();
        timer.start();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Diseño/Icono.png"));
        setIconImage(icon);
        lblfecha.setText(cmbfecha.getSelectedItem().toString());
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Diseño/Login.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbfecha = new org.freixas.jcalendar.JCalendarCombo();
        lblhora = new javax.swing.JLabel();
        MenuEmergente = new javax.swing.JPopupMenu();
        MenuMinimizar = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();
        panelTranslucidoComplete1 = new org.edisoncor.gui.panel.PanelTranslucidoComplete();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel2 = new javax.swing.JLabel();
        txtContraseña = new org.edisoncor.gui.passwordField.PasswordFieldRound();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        lblRecuperar = new javax.swing.JLabel();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        DigitalClk = new org.edisoncor.gui.varios.ClockDigital();
        panelRectTranslucido2 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        lblfecha = new javax.swing.JLabel();

        lblhora.setText("jLabel3");

        MenuMinimizar.setText("Minimizar");
        MenuMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMinimizarActionPerformed(evt);
            }
        });
        MenuEmergente.add(MenuMinimizar);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        MenuEmergente.add(MenuSalir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        BtnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnAceptar.setContentAreaFilled(false);
        BtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAceptar.setFocusable(false);
        BtnAceptar.setOpaque(true);
        BtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseExited(evt);
            }
        });
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnCancelar.setContentAreaFilled(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.setFocusable(false);
        BtnCancelar.setOpaque(true);
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseExited(evt);
            }
        });
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/1.png"))); // NOI18N

        lblRecuperar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRecuperar.setForeground(new java.awt.Color(255, 255, 255));
        lblRecuperar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperar.setText("Restablecer contraseña");
        lblRecuperar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucidoComplete1Layout = new javax.swing.GroupLayout(panelTranslucidoComplete1);
        panelTranslucidoComplete1.setLayout(panelTranslucidoComplete1Layout);
        panelTranslucidoComplete1Layout.setHorizontalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addComponent(lblIcono)
                        .addGap(43, 43, 43)
                        .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelTranslucidoComplete1Layout.setVerticalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lblRecuperar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        DigitalClk.setForeground(new java.awt.Color(255, 255, 255));
        DigitalClk.setFont(new java.awt.Font("DS-Digital", 1, 24)); // NOI18N

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DigitalClk, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DigitalClk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblfecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRectTranslucido2Layout = new javax.swing.GroupLayout(panelRectTranslucido2);
        panelRectTranslucido2.setLayout(panelRectTranslucido2Layout);
        panelRectTranslucido2Layout.setHorizontalGroup(
            panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido2Layout.createSequentialGroup()
                .addComponent(lblfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRectTranslucido2Layout.setVerticalGroup(
            panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(panelTranslucidoComplete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelRectTranslucido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelTranslucidoComplete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(panelRectTranslucido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseEntered
        BtnAceptar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnAceptarMouseEntered

    private void BtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseExited
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnAceptarMouseExited

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        if(txtUsuario.getText().isEmpty() || txtContraseña.getText().isEmpty()){
            MtoIntentosFallidos();
        }
        else{
            try {
                PreparedStatement st = cn.prepareStatement("SELECT codigo_usuario, nombres, apellidos, usuario, codigo_tipo_usuario FROM usuarios WHERE usuario = ? AND contraseña = CONVERT(VARCHAR(32), HashBytes('MD5', ?), 2)");
                st.setString(1, txtUsuario.getText());
                st.setString(2, txtContraseña.getText());
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    ClsSQLQuery.ProCodigoUsuario = rs.getInt(1);
                    ClsSQLQuery.ProNombresUsuario = rs.getString(2);
                    ClsSQLQuery.ProApellidosUsuario = rs.getString(3);
                    ClsSQLQuery.ProNombreUsuario = rs.getString(4);
                    ClsSQLQuery.ProTipoUsuario = rs.getInt(5);
                    JOptionPane.showMessageDialog(this, "Bienvenid@ " + ClsSQLQuery.ProNombreUsuario, "Welcome", JOptionPane.INFORMATION_MESSAGE);
                    st = cn.prepareStatement("INSERT INTO historial(usuario, hora, fecha) VALUES(?, ?, ?)");
                    st.setString(1, ClsSQLQuery.ProNombreUsuario);
                    st.setString(2, lblhora.getText());
                    st.setString(3, lblfecha.getText());
                    st.executeUpdate();
                    ClsSonidos.Sesion();
                    FrmPrincipal obj = new FrmPrincipal();
                    obj.setVisible(true);
                    dispose();
                }
                else{
                    MtoIntentosFallidos();
                }
            } catch (SQLException | HeadlessException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseEntered
        BtnCancelar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnCancelarMouseEntered

    private void BtnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseExited
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnCancelarMouseExited

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        JOptionPane.showMessageDialog(this, "No podras usar el sistema si no inicias sesión", "AVISO", JOptionPane.ERROR_MESSAGE, ClsIconos.Error);
        System.exit(0);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void lblRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseClicked
        FrmTipoRecuperacion obj = new FrmTipoRecuperacion(this, true);
        obj.setVisible(true);
    }//GEN-LAST:event_lblRecuperarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i + "F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void lblRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseEntered
        lblRecuperar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_lblRecuperarMouseEntered

    private void lblRecuperarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseExited
        lblRecuperar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_lblRecuperarMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getButton() == 3)
        {
            MenuEmergente.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void MenuMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMinimizarActionPerformed
        setExtendedState(1);
    }//GEN-LAST:event_MenuMinimizarActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Desea salir del sistema?", "AVISO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenuSalirActionPerformed

    int intentos = 0;
    void MtoIntentosFallidos()
        {
            intentos = intentos + 1;
            if (intentos < 3)
            {
                ClsSonidos.IntentosFallidos();
                JOptionPane.showMessageDialog(this, "¡Datos incorrectos!", "ERROR", JOptionPane.CANCEL_OPTION);
                txtUsuario.setText(null);
                txtContraseña.setText(null);
                txtUsuario.requestFocusInWindow();
            }
            else
            {
                ClsSonidos.IntentosFallidos();
                JOptionPane.showMessageDialog(this, "¡Intentos fallidos!", "ERROR", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
    
    private void obtenerDatos(){
        hora = calendar.get(Calendar.HOUR_OF_DAY);
        minuto = calendar.get(Calendar.MINUTE);
        segundo = calendar.get(Calendar.SECOND);
    }
    private void mostrarDatos(){
        lblhora.setText(hora + " : " + minuto + " : " + segundo);
    }
    
    private void validarHora(){
        if(segundo == 59){
            minuto++;
            segundo = 0;
            if(minuto == 59){
                hora++;
                minuto = 0;
                if(hora == 23){
                    hora = 0;
                }
            }
        }else{
                segundo++;
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSesión().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private org.edisoncor.gui.varios.ClockDigital DigitalClk;
    private javax.swing.JPopupMenu MenuEmergente;
    private javax.swing.JMenuItem MenuMinimizar;
    private javax.swing.JMenuItem MenuSalir;
    private org.freixas.jcalendar.JCalendarCombo cmbfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblRecuperar;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido2;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete panelTranslucidoComplete1;
    private org.edisoncor.gui.passwordField.PasswordFieldRound txtContraseña;
    private org.edisoncor.gui.textField.TextFieldRound txtUsuario;
    // End of variables declaration//GEN-END:variables
ClsConexion cc= new ClsConexion();
Connection cn= cc.conectar();
}
