/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.ClsConexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Will Vasquez
 */
public final class RevisionVehiculos extends javax.swing.JDialog {
private Timer t;
private ActionListener Act;
String estado;

    /**
     * Creates new form RevisionVehiculos
     * @param parent
     * @param modal
     */
    public RevisionVehiculos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Revision de vehiculos");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Diseño/Icono.png"));
        setIconImage(icon);
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Diseño/Revision.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }
    
    public String getEstado() {
        return estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbvehiculo = new javax.swing.JComboBox();
        Chk_pintura = new javax.swing.JCheckBox();
        Chk_tapiceria = new javax.swing.JCheckBox();
        Chk_neumaticos = new javax.swing.JCheckBox();
        Chk_aceite = new javax.swing.JCheckBox();
        Chk_agua = new javax.swing.JCheckBox();
        Chk_transm = new javax.swing.JCheckBox();
        Chk_suspension = new javax.swing.JCheckBox();
        Chk_frenos = new javax.swing.JCheckBox();
        Chk_direccion = new javax.swing.JCheckBox();
        Chk_sisElect = new javax.swing.JCheckBox();
        lblestado = new javax.swing.JLabel();
        BtnIniciar = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Revision", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white)); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehiculo:");

        cmbvehiculo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        Chk_pintura.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_pintura.setForeground(new java.awt.Color(255, 255, 255));
        Chk_pintura.setText("Pintura");
        Chk_pintura.setOpaque(false);

        Chk_tapiceria.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_tapiceria.setForeground(new java.awt.Color(255, 255, 255));
        Chk_tapiceria.setText(" Tapicería");
        Chk_tapiceria.setOpaque(false);

        Chk_neumaticos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_neumaticos.setForeground(new java.awt.Color(255, 255, 255));
        Chk_neumaticos.setText(" Neumáticos");
        Chk_neumaticos.setOpaque(false);

        Chk_aceite.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_aceite.setForeground(new java.awt.Color(255, 255, 255));
        Chk_aceite.setText("Nivel de aceite");
        Chk_aceite.setOpaque(false);

        Chk_agua.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_agua.setForeground(new java.awt.Color(255, 255, 255));
        Chk_agua.setText("Nivel de agua");
        Chk_agua.setOpaque(false);

        Chk_transm.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_transm.setForeground(new java.awt.Color(255, 255, 255));
        Chk_transm.setText(" Transmisión");
        Chk_transm.setOpaque(false);

        Chk_suspension.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_suspension.setForeground(new java.awt.Color(255, 255, 255));
        Chk_suspension.setText("Suspensión");
        Chk_suspension.setOpaque(false);

        Chk_frenos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_frenos.setForeground(new java.awt.Color(255, 255, 255));
        Chk_frenos.setText("Frenos");
        Chk_frenos.setOpaque(false);

        Chk_direccion.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_direccion.setForeground(new java.awt.Color(255, 255, 255));
        Chk_direccion.setText("Dirección ");
        Chk_direccion.setOpaque(false);

        Chk_sisElect.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_sisElect.setForeground(new java.awt.Color(255, 255, 255));
        Chk_sisElect.setText(" Sistema eléctrico");
        Chk_sisElect.setOpaque(false);

        lblestado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        BtnIniciar.setBackground(new java.awt.Color(0, 0, 0));
        BtnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIniciar.setText("Iniciar");
        BtnIniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnIniciar.setContentAreaFilled(false);
        BtnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIniciar.setFocusable(false);
        BtnIniciar.setOpaque(true);
        BtnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnIniciarMouseExited(evt);
            }
        });
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chk_transm)
                            .addComponent(Chk_pintura)
                            .addComponent(Chk_frenos)
                            .addComponent(Chk_suspension))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chk_tapiceria)
                            .addComponent(Chk_aceite)
                            .addComponent(Chk_direccion)
                            .addComponent(Chk_neumaticos))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Chk_sisElect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Chk_agua)
                            .addComponent(BtnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblestado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblestado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_pintura)
                    .addComponent(Chk_tapiceria)
                    .addComponent(Chk_agua))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_transm)
                    .addComponent(Chk_sisElect)
                    .addComponent(Chk_aceite))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chk_frenos)
                            .addComponent(Chk_direccion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chk_suspension)
                            .addComponent(Chk_neumaticos))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CargarDatos();
        cmbvehiculo.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        if(cmbvehiculo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un vehiculo", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if(!(Chk_aceite.isSelected() || Chk_agua.isSelected() || Chk_direccion.isSelected() || Chk_frenos.isSelected() || Chk_neumaticos.isSelected() || Chk_transm.isSelected() || Chk_tapiceria.isSelected() || Chk_suspension.isSelected() || Chk_sisElect.isSelected() || Chk_pintura.isSelected())){
            JOptionPane.showMessageDialog(this, "¡Debe seleccionar al menos un tipo de revision!", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            Act = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    if (ProgressBar.getValue() < 100) {
                        ProgressBar.setValue(ProgressBar.getValue()+1);
                    }
                    else {
                        t.stop();
                        cerrar();
                    }
                }
            };
            t = new Timer(15, Act);
            t.start();
        }
    }//GEN-LAST:event_BtnIniciarActionPerformed

    private void BtnIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIniciarMouseEntered
        BtnIniciar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnIniciarMouseEntered

    private void BtnIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIniciarMouseExited
        BtnIniciar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnIniciarMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(this, "No puedes salir hasta que finalices la revision", "AVISO", JOptionPane.CANCEL_OPTION);
    }//GEN-LAST:event_formWindowClosing

    public void CargarDatos() 
    {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT (cast(codigo_vehiculo AS varchar(50)) + ' - ' + marca + ', ' + modelo) AS nombre FROM vehiculos ORDER BY marca");
            cmbvehiculo.removeAllItems();
            while(rs.next())
            {
                cmbvehiculo.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cerrar(){
        JOptionPane.showMessageDialog(this, "Revision finalizada con exito", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        lblestado.setText("Revision finalizada");
        estado = this.lblestado.getText();
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                RevisionVehiculos dialog = new RevisionVehiculos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JCheckBox Chk_aceite;
    private javax.swing.JCheckBox Chk_agua;
    private javax.swing.JCheckBox Chk_direccion;
    private javax.swing.JCheckBox Chk_frenos;
    private javax.swing.JCheckBox Chk_neumaticos;
    private javax.swing.JCheckBox Chk_pintura;
    private javax.swing.JCheckBox Chk_sisElect;
    private javax.swing.JCheckBox Chk_suspension;
    private javax.swing.JCheckBox Chk_tapiceria;
    private javax.swing.JCheckBox Chk_transm;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JComboBox cmbvehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblestado;
    // End of variables declaration//GEN-END:variables
ClsConexion cc= new ClsConexion();
Connection cn= cc.conectar();
}
