/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.ClsConexion;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Will Vasquez
 */
public class TipoUsuario extends javax.swing.JDialog {
DefaultTableModel modelo;
    /**
     * Creates new form TipoUsuario
     * @param parent
     * @param modal
     */
    public TipoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Tipo de usuarios");
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Diseño/TipoUsuario.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnlDescripcion2 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        Chk_usuarios = new javax.swing.JCheckBox();
        Chk_tipo = new javax.swing.JCheckBox();
        Chk_flota = new javax.swing.JCheckBox();
        Chk_clientes = new javax.swing.JCheckBox();
        Chk_aquiler = new javax.swing.JCheckBox();
        Chk_reportes = new javax.swing.JCheckBox();
        Chk_conta = new javax.swing.JCheckBox();
        BtnAgregar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnConsultar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        Btnlimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), java.awt.Color.white)); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo:");

        txtcodigo.setEditable(false);
        txtcodigo.setEnabled(false);
        txtcodigo.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtcodigoTextValueChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre tipo:");

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion:");

        txtdescripcion.setColumns(20);
        txtdescripcion.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtdescripcion.setLineWrap(true);
        txtdescripcion.setRows(2);
        txtdescripcion.setWrapStyleWord(true);
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyTyped(evt);
            }
        });
        spnlDescripcion2.setViewportView(txtdescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnlDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtnombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spnlDescripcion2))
                .addContainerGap())
        );

        Chk_usuarios.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Chk_usuarios.setText("Usuarios");
        Chk_usuarios.setOpaque(false);

        Chk_tipo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_tipo.setForeground(new java.awt.Color(255, 255, 255));
        Chk_tipo.setText("Tipo usuarios");
        Chk_tipo.setOpaque(false);

        Chk_flota.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_flota.setForeground(new java.awt.Color(255, 255, 255));
        Chk_flota.setText("Flota");
        Chk_flota.setOpaque(false);

        Chk_clientes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_clientes.setForeground(new java.awt.Color(255, 255, 255));
        Chk_clientes.setText("Clientes");
        Chk_clientes.setOpaque(false);

        Chk_aquiler.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_aquiler.setForeground(new java.awt.Color(255, 255, 255));
        Chk_aquiler.setText("Alquileres");
        Chk_aquiler.setOpaque(false);

        Chk_reportes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_reportes.setForeground(new java.awt.Color(255, 255, 255));
        Chk_reportes.setText("Reportes");
        Chk_reportes.setOpaque(false);

        Chk_conta.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Chk_conta.setForeground(new java.awt.Color(255, 255, 255));
        Chk_conta.setText("Contaduria");
        Chk_conta.setOpaque(false);

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chk_clientes)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chk_usuarios)
                            .addComponent(Chk_tipo)
                            .addComponent(Chk_flota))
                        .addGap(41, 41, 41)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chk_conta)
                            .addComponent(Chk_reportes)
                            .addComponent(Chk_aquiler))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_usuarios)
                    .addComponent(Chk_aquiler))
                .addGap(18, 18, 18)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_tipo)
                    .addComponent(Chk_reportes))
                .addGap(18, 18, 18)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_flota)
                    .addComponent(Chk_conta))
                .addGap(18, 18, 18)
                .addComponent(Chk_clientes)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnAgregar.setContentAreaFilled(false);
        BtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregar.setFocusable(false);
        BtnAgregar.setOpaque(true);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseExited(evt);
            }
        });
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnModificar.setBackground(new java.awt.Color(0, 0, 0));
        BtnModificar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Modificar");
        BtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnModificar.setContentAreaFilled(false);
        BtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnModificar.setFocusable(false);
        BtnModificar.setOpaque(true);
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnModificarMouseExited(evt);
            }
        });
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnConsultar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultar.setText("Consultar");
        BtnConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnConsultar.setContentAreaFilled(false);
        BtnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConsultar.setFocusable(false);
        BtnConsultar.setOpaque(true);
        BtnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnConsultarMouseExited(evt);
            }
        });
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BtnEliminar.setContentAreaFilled(false);
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.setFocusable(false);
        BtnEliminar.setOpaque(true);
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseExited(evt);
            }
        });
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        Btnlimpiar.setBackground(new java.awt.Color(0, 0, 0));
        Btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        Btnlimpiar.setText("Limpiar");
        Btnlimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Btnlimpiar.setContentAreaFilled(false);
        Btnlimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btnlimpiar.setFocusable(false);
        Btnlimpiar.setOpaque(true);
        Btnlimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnlimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnlimpiarMouseExited(evt);
            }
        });
        Btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlimpiarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelCurves1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyTyped
        if (txtdescripcion.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdescripcionKeyTyped

    private void BtnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseEntered
        BtnAgregar.setForeground(new java.awt.Color(51, 153, 255));
    }//GEN-LAST:event_BtnAgregarMouseEntered

    private void BtnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseExited
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BtnAgregarMouseExited

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if(txtnombre.getText().isEmpty() || txtdescripcion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No puedes dejar campos en blanco", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if(!(Chk_usuarios.isSelected() || Chk_reportes.isSelected() || Chk_aquiler.isSelected() || Chk_clientes.isSelected() || Chk_conta.isSelected() || Chk_flota.isSelected() || Chk_tipo.isSelected())){
            JOptionPane.showMessageDialog(this, "¡Debe seleccionar al menos un permiso para crear un tipo de usuario!", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            try {
                PreparedStatement st = cn.prepareStatement("SELECT nombre FROM tipo_usuario WHERE nombre = ?");
                st.setString(1, txtnombre.getText());
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Ya existe este tipo de usuario", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                    st = cn.prepareStatement("INSERT INTO tipo_usuario VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)");
                    st.setString(1, txtnombre.getText());
                    st.setString(2, txtdescripcion.getText());
                    st.setBoolean(3, Chk_usuarios.isSelected());
                    st.setBoolean(4, Chk_tipo.isSelected());
                    st.setBoolean(5, Chk_flota.isSelected());
                    st.setBoolean(6, Chk_clientes.isSelected());
                    st.setBoolean(7, Chk_aquiler.isSelected());
                    st.setBoolean(8, Chk_reportes.isSelected());
                    st.setBoolean(9, Chk_conta.isSelected());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Datos agredados", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                    MostrarDatos();
                    Limpiar();
                }
            } catch (Exception e) {
            }
    }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarMouseEntered

    private void BtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarMouseExited

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        if(txtnombre.getText().isEmpty() || txtdescripcion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No puedes dejar campos en blanco", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if(!(Chk_usuarios.isSelected() || Chk_reportes.isSelected() || Chk_aquiler.isSelected() || Chk_clientes.isSelected() || Chk_conta.isSelected() || Chk_flota.isSelected() || Chk_tipo.isSelected())){
            JOptionPane.showMessageDialog(this, "¡Debe seleccionar al menos un permiso para crear un tipo de usuario!", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro para modificar", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            try {
                PreparedStatement st = cn.prepareStatement("SELECT nombre FROM tipo_usuario WHERE nombre = ? AND NOT codigo_tipo_usuario = ?");
                st.setString(1, txtnombre.getText());
                st.setInt(2, Integer.parseInt(txtcodigo.getText()));
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Ya existe este tipo de usuario", "AVISO", JOptionPane.CANCEL_OPTION);
                }
                else{
                    st = cn.prepareStatement("UPDATE tipo_usuario SET nombre_tipo = ?, descripcion = ?, usuario = ?, tipo_usuario = ?, flota = ?, clientes = ?, alquileres = ?, reportes = ?, contaduria = ? WHERE codigo_tipo_usuario = ?");
                    st.setString(1, txtnombre.getText());
                    st.setString(2, txtdescripcion.getText());
                    st.setBoolean(3, Chk_usuarios.isSelected());
                    st.setBoolean(4, Chk_tipo.isSelected());
                    st.setBoolean(5, Chk_flota.isSelected());
                    st.setBoolean(6, Chk_clientes.isSelected());
                    st.setBoolean(7, Chk_aquiler.isSelected());
                    st.setBoolean(8, Chk_reportes.isSelected());
                    st.setBoolean(9, Chk_conta.isSelected());
                    st.setInt(10, Integer.parseInt(txtcodigo.getText()));
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Datos modificados", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                    MostrarDatos();
                    Limpiar();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConsultarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsultarMouseEntered

    private void BtnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConsultarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsultarMouseExited

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        MostrarDatos();
    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void BtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarMouseEntered

    private void BtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarMouseExited

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if("".equals(txtcodigo.getText())) {
            JOptionPane.showMessageDialog(this, "¡Debe realizar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else if("1".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "No puedes eliminar al administrador del sistema", "AVISO", JOptionPane.CANCEL_OPTION);
        }
        else{
            try{
            PreparedStatement st = cn.prepareStatement("DELETE FROM tipo_usuario WHERE codigo_tipo_usuario = ?");
            st.setInt(1, Integer.parseInt(txtcodigo.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar?", "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(eliminar == 0){
                st.execute();
                    int filaselecionada= Tabla.getSelectedRow();
                    if(filaselecionada>=0){
                    modelo.removeRow(filaselecionada);
                    JOptionPane.showMessageDialog(this, "Datos eliminados");
                    Limpiar();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Error al eliminar");
                    }
                }
            }catch(SQLException | NumberFormatException | HeadlessException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnlimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnlimpiarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnlimpiarMouseEntered

    private void BtnlimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnlimpiarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnlimpiarMouseExited

    private void BtnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlimpiarActionPerformed
        Limpiar();
        Tabla.setModel(new DefaultTableModel());
    }//GEN-LAST:event_BtnlimpiarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        txtcodigo.setText(Tabla.getValueAt(Tabla.getSelectedRow(), 0).toString());
        txtnombre.setText(Tabla.getValueAt(Tabla.getSelectedRow(), 1).toString());
        txtdescripcion.setText(Tabla.getValueAt(Tabla.getSelectedRow(), 2).toString());
        if ("1".equals(Tabla.getValueAt(Tabla.getSelectedRow(), 3).toString())) {
                        Chk_usuarios.setSelected(true);
                    }
                    else {
                        Chk_usuarios.setSelected(false);
                    }
        if ("1".equals(Tabla.getValueAt(Tabla.getSelectedRow(), 4).toString())) {
                        Chk_tipo.setSelected(true);
                    }
                    else {
                        Chk_tipo.setSelected(false);
                    }
        if ("1".equals(Tabla.getValueAt(Tabla.getSelectedRow(), 5).toString())) {
                        Chk_flota.setSelected(true);
                    }
                    else {
                        Chk_flota.setSelected(false);
                    }
        if ("1".equals(Tabla.getValueAt(Tabla.getSelectedRow(), 6).toString())) {
                        Chk_clientes.setSelected(true);
                    }
                    else {
                        Chk_clientes.setSelected(false);
                    }
        if ("1".equals(Tabla.getValueAt(Tabla.getSelectedRow(), 7).toString())) {
                        Chk_aquiler.setSelected(true);
                    }
                    else {
                        Chk_aquiler.setSelected(false);
                    }
        if ("1".equals(Tabla.getValueAt(Tabla.getSelectedRow(), 7).toString())) {
                        Chk_reportes.setSelected(true);
                    }
                    else {
                        Chk_reportes.setSelected(false);
                    }
        if ("1".equals(Tabla.getValueAt(Tabla.getSelectedRow(), 7).toString())) {
                        Chk_conta.setSelected(true);
                    }
                    else {
                        Chk_conta.setSelected(false);
                    }
    }//GEN-LAST:event_TablaMouseClicked

    private void txtcodigoTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtcodigoTextValueChanged
        Chk_usuarios.setEnabled(!txtcodigo.getText().equals("1"));
        Chk_tipo.setEnabled(!txtcodigo.getText().equals("1"));
        Chk_flota.setEnabled(!txtcodigo.getText().equals("1"));
        Chk_clientes.setEnabled(!txtcodigo.getText().equals("1"));
        Chk_aquiler.setEnabled(!txtcodigo.getText().equals("1"));
        Chk_reportes.setEnabled(!txtcodigo.getText().equals("1"));
        Chk_conta.setEnabled(!txtcodigo.getText().equals("1"));
    }//GEN-LAST:event_txtcodigoTextValueChanged

    void Limpiar(){
        txtcodigo.setText(null);
        txtnombre.setText(null);
        txtdescripcion.setText(null);
        Chk_usuarios.setSelected(false);
        Chk_tipo.setSelected(false);
        Chk_flota.setSelected(false);
        Chk_clientes.setSelected(false);
        Chk_aquiler.setSelected(false);
        Chk_reportes.setSelected(false);
        Chk_conta.setSelected(false);
    }
    
    void MostrarDatos()
    {
    modelo= new DefaultTableModel();
    modelo.addColumn("Codigo");
    modelo.addColumn("Nombre");
    modelo.addColumn("Descripcion");
    modelo.addColumn("Usuarios");
    modelo.addColumn("Tipo usuarios");
    modelo.addColumn("Flota");
    modelo.addColumn("Clientes");
    modelo.addColumn("Alquileres");
    modelo.addColumn("Reportes");
    modelo.addColumn("Contaduria");
    Tabla.setModel(modelo);
    String sql="SELECT * FROM tipo_usuario";
    String []datos = new String [10];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                modelo.addRow(datos);
            }
            Tabla.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(TipoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TipoUsuario dialog = new TipoUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton Btnlimpiar;
    private javax.swing.JCheckBox Chk_aquiler;
    private javax.swing.JCheckBox Chk_clientes;
    private javax.swing.JCheckBox Chk_conta;
    private javax.swing.JCheckBox Chk_flota;
    private javax.swing.JCheckBox Chk_reportes;
    private javax.swing.JCheckBox Chk_tipo;
    private javax.swing.JCheckBox Chk_usuarios;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private javax.swing.JScrollPane spnlDescripcion2;
    private java.awt.TextField txtcodigo;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
ClsConexion cc= new ClsConexion();
Connection cn= cc.conectar();
}
